stages:
    load_data:
        cmd: python src/stages/load_data.py --config=params.yaml
        deps:
        - src/stages/load_data.py
        params:
        - load_data
        - trainer
        outs:
        - "data/cleaned_data"
        
    tokenize_data:
        cmd: python src/stages/preprocessing_data.py --config=params.yaml
        deps:
        - src/stages/preprocessing_data.py
        - "data/cleaned_data"
        params:
        - tokenize_data
        outs:
        - "data/tokenized_data"
    
    train:
        cmd: python src/stages/trainer.py --config=params.yaml
        deps:
        - src/stages/trainer.py
        - src/models/Trainer.py
        - src/models/modeling_bert.py
        - "data/tokenized_data"
        params:
        - trainer
        outs:
        - "artifacts/sentiment_classifier"
        plots:
        - reports/train_loss.csv:
            x: batches
            y: train_loss
            title: Training Losses Per Batches
        - reports/eval_loss.csv:
            x: batches
            y: valid_loss
            title: Validation Loss Per Batch
            
    test_data:
        cmd: python src/stages/test_model.py --config="params.yaml" --predict="i love thos movie"
        deps:
        - src/stages/test_model.py
        - "artifacts/sentiment_classifier"
        params:
        - tester
        outs:
        - "reports/predictions"
        plots:
        - predictions/scores.png
        metrics:
        - metrics/vaild_metrics.json
        - metrics/test_metrics.json